# -*- mode: ruby -*-
# vi: set ft=ruby :

#Place Vagrantfile in the directory you run vagrant from.
#This should also contain ubuntu.yml which configure VMs

# setting for all VMs
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "jumpbox" do |jumpbox|
    jumpbox.vm.box = "debian/bookworm64"
	jumpbox.vm.hostname = "jumpbox"
	jumpbox.vm.network "private_network", ip: "192.168.60.5"
  end

  config.vm.define "server" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.60.10"
  end

  config.vm.define "node0" do |node0|
    node0.vm.box = "debian/bookworm64"
    node0.vm.hostname = "node-0"
    node0.vm.network "private_network", ip: "192.168.60.11"
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "debian/bookworm64"
    node1.vm.hostname = "node-1"
    node1.vm.network "private_network", ip: "192.168.60.12"
  end

end
