# -*- mode: ruby -*-
# vi: set ft=ruby :

#Place Vagrantfile in the directory you run vagrant from.
#This should also contain ubuntu.yml which configure VMs

# setting for all VMs
Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.provision "ansible_local", playbook: "ubuntu.yml"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.60.110"

	ubuntu.vm.provider "virtualbox" do |vb|
	  vb.memory = 1024
	  vb.cpus = 1
	end
  end

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "rockylinux/9"
    rocky.vm.hostname = "rocky"
    rocky.vm.network "private_network", ip: "192.168.60.111"

	rocky.vm.provider "virtualbox" do |vb|
	  vb.memory = 1024
	  vb.cpus = 1
	end
  end
end
