# -*- mode: ruby -*-
# vi: set ft=ruby :

#Place Vagrantfile in the directory you run vagrant from.
#This should also contain ubuntu.yml which configure VMs

# setting for all VMs
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  # specific for tosser
  config.vm.define "tosser" do |tosser|
    tosser.vm.box = "ubuntu/jammy64"
    tosser.vm.provision "ansible_local", playbook: "ubuntu_with_docker.yml"
    tosser.vm.hostname = "playground"
    tosser.vm.network "private_network", ip: "192.168.60.120"
  end
end
