# -*- mode: ruby -*-
# vi: set ft=ruby :

#Place Vagrantfile in the directory you run vagrant from.
#This should also contain ubuntu.yml which configure VMs

# setting for all VMs
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # specific for ubuntu1
  config.vm.define "playground" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.provision "ansible_local", playbook: "ubuntu_with_docker.yml"
    ubuntu1.vm.hostname = "playground"
    ubuntu1.vm.network "private_network", ip: "192.168.60.120"
  end
end
